### ISSUE TITLE
Crash when destructing AnnotatedDataLayer

### ISSUE THREAD

**Issue by peyer** [maidabu/caffe-ssd-optimized#1]
@maidabu Thanks for your effort of optimization! I replaced original ssd code with your annotated_data_layer.cpp and data_transform.cpp and started train process, it also completed iterations and accelerated train process. 
But when destructing AnnotatedDataLayer, it comment crash. Did you have some suggestion?

**Comment by maidabu** [comment]
I have fix the bug.Thanks for your question.

**Comment by peyer** [comment]
@maidabu Thanks for your reply. I have test your new release code and succesfully run the whole training progress. I tried to use std::vector<Blob<Dtype> > xxx to replace yours shared_ptr<Blob<Dtype> >transformed_data_array_ before got your reply,  but got error indication that caffe::Blob<Dtype> is private ... Sorry for my poor abality of coding.
